---
title: "Untitled"
output: html_document
date: "2023-10-17"
---
```{r}
library(dplyr)
```

```{r}
library(haven)
 wave1 <- read_dta("~/git/values/WV1_Data_stata_v20200208.dta")
 wave2<- read_dta("~/git/values/WV2_Data_Stata_v20180912.dta")
 wave3= read_dta("~/git/values/WV3_Data_Stata_v20180912.dta")
 wave4=read_dta("~/git/values/WV4_Data_stata_v20201117.dta")

 
```



```{r}
library(dplyr)

wave1select <- wave1 %>%
  rename(
    "religious denomination" = V179,
    "Self positioning in political scale" =V123,
    "age" = V216,
    "Socio-economic status of respondent"=V226,
    "employment" = V220,
    "sex" = V214,
    "cheat"=V192,
    "educ"=V218
  ) %>%
  select("religious denomination", "Self positioning in political scale", "age", "employment", "sex","cheat","educ","Socio-economic status of respondent")

wave2select <- wave2 %>%
  rename(
    "religious denomination" = V144,
    "Self positioning in political scale" = V248,
    "sex" = V353,
    "employment" = V358,
    "age" = V355,
    "Socio-economic status of respondent"=V364,
    "cheat"=V296,
    "educ"=V356
  ) %>%
  select("religious denomination", "Self positioning in political scale", "age", "employment", "sex","cheat","educ","Socio-economic status of respondent")

wave3select <- wave3 %>%
  rename(
    "religious denomination" = V179,
    "Self positioning in political scale" = V123,
    "age" = V216,
    "sex" = V214,
    "cheat"=V192,
    "Socio-economic status of respondent"=V226,
    "employment" = V220
  ,"educ"=V218
  ) %>%
  select("religious denomination", "Self positioning in political scale", "age", "employment", "sex","cheat","educ","Socio-economic status of respondent")

wave4select <- wave4 %>%
  rename(
    "religious denomination" = V184G,
    "Self positioning in political scale" =V139,
    "age" = V225,
    "sex" = V223,
    "employment" = V229,
    "educ"=V227,
    "Socio-economic status of respondent"=V235,
    "cheat"=V204
  ) %>%
  select("religious denomination", "Self positioning in political scale", "age", "employment", "sex","educ","cheat","Socio-economic status of respondent")

# Step 2: Add a 'Year' column to each data frame
wave1select$Year <- 1980
wave2select$Year <- 1990
wave3select$Year <- 1995
wave4select$Year <- 1999
```
```{r}
wave1select <- wave1select %>%
  mutate(`Socio-economic status of respondent` = case_when(
    `Socio-economic status of respondent` == 1 ~ "Upper class",
    `Socio-economic status of respondent` == 2 ~ "upper middle class",
    `Socio-economic status of respondent` == 3 ~ "Low middle class", # Assuming 'Skilled' is similar to 'Low middle class'
   
    `Socio-economic status of respondent` == -2 ~ NA_character_,
      `Socio-economic status of respondent` == -4 ~ NA_character_
    
   , # Don't know
    TRUE ~ NA_character_ # Any other values will be set to NA
  ))
```

```{r}
wave2select <- wave2select %>%
  mutate(`Socio-economic status of respondent` = case_when(
    `Socio-economic status of respondent` == 1 ~ "Upper class",
    `Socio-economic status of respondent` == 2 ~ "Upper middle class",
    `Socio-economic status of respondent` == 3 ~ "Low middle class",
    `Socio-economic status of respondent` == 4 ~ "Low middle class", # Assuming 'Skilled' is similar to 'Low middle class'
    `Socio-economic status of respondent` == 5 ~ "Low middle class", # Assuming 'Unskill' is similar to 'Low middle class'
    `Socio-economic status of respondent` == -5 ~ NA_character_, # Missing; Unknown; Inappropriate
    `Socio-economic status of respondent` == -4 ~ NA_character_, # Not asked
    `Socio-economic status of respondent` == -3 ~ NA_character_, # Not applicable
    `Socio-economic status of respondent` == -2 ~ NA_character_, # No answer
    `Socio-economic status of respondent` == -1 ~ NA_character_, # Don't know
    TRUE ~ NA_character_ # Any other values will be set to NA
  ))

```
```{r}
wave1select$`religious denomination`=wave1select$`religious denomination`%>%as.numeric()
```

```{r}
wave3select <- wave3select %>%
  mutate(`Socio-economic status of respondent` = case_when(
    `Socio-economic status of respondent` == 1 ~ "Upper class",
    `Socio-economic status of respondent` == 2 ~ "Upper middle class",
    `Socio-economic status of respondent` == 3 ~ "Low middle class",
    `Socio-economic status of respondent` == 4 ~ "Low middle class", # Assuming 'Working class' is similar to 'Low middle class'
    `Socio-economic status of respondent` == 5 ~ "Low middle class", # Assuming 'Lower class' is similar to 'Low middle class'
    `Socio-economic status of respondent` == -2 ~ NA_character_, # NA
    `Socio-economic status of respondent` == -1 ~ NA_character_, # DK (Don't know)
    `Socio-economic status of respondent` == -4 ~ NA_character_, # Not asked
    TRUE ~ NA_character_ # Any other values will be set to NA
  ))

```
```{r}
wave4select <- wave4select %>%
  mutate(`Socio-economic status of respondent` = case_when(
    `Socio-economic status of respondent` == 1 ~ "Upper class",
    `Socio-economic status of respondent` == 2 ~ "Upper middle class",
    `Socio-economic status of respondent` == 3 ~ "Low middle class",
    `Socio-economic status of respondent` == 4 ~ "Low middle class", # Assuming 'Working class' is similar to 'Low middle class'
    `Socio-economic status of respondent` == 5 ~ "Low middle class", # Assuming 'Lower class' is similar to 'Low middle class'
    `Socio-economic status of respondent` == -2 ~ NA_character_, # No answer
    `Socio-economic status of respondent` == -1 ~ NA_character_, # Don't know
    `Socio-economic status of respondent` == -4 ~ NA_character_, # Not asked
    TRUE ~ NA_character_ # Any other values will be set to NA
  ))

```

```{r}
wave2select <- wave2select %>%
  mutate(`religious denomination` = case_when(
    `religious denomination` == 0  ~ 0,
    `religious denomination` == 64 ~ 1,
    `religious denomination` == 62 ~ 2,
    `religious denomination` == 49 ~ 3,
    `religious denomination` == 42 ~ 4,
    `religious denomination` == 43 ~ 5,
    `religious denomination` == 28 ~ 6,
    `religious denomination` == 12 ~ 7,
    `religious denomination` == 53 ~ 8,
    `religious denomination` == -2 ~ -2,
    `religious denomination` == -4 ~ -4,
    `religious denomination` == -5 ~ -5,
    TRUE ~ NA_integer_ # Other values will be set to NA
  ))



```
```{r}

wave3select <- wave3select %>%
  mutate(`religious denomination` = case_when(
    `religious denomination` == 96 ~ 0,
    `religious denomination` == 1  ~ 1,
    `religious denomination` == 2  ~ 2,
    `religious denomination` == 3  ~ 3,
    `religious denomination` == 4  ~ 4,
    `religious denomination` == 5  ~ 5,
    `religious denomination` == 6  ~ 6,
    `religious denomination` == 7  ~ 7,
    `religious denomination` == 80 ~ 8,  # and possibly other categories as 'Other'
    `religious denomination` == 99 ~ -2,
    `religious denomination` == 100 ~ -4,
    `religious denomination` == 98 ~ -5,
    TRUE ~ NA_integer_  # to discard other categories not listed
  ))


```
```{r}
wave4select <- wave4select %>%
  mutate(`religious denomination` = case_when(
    `religious denomination` == -5 ~ -5,  # Mapping "Missing" to -5
    `religious denomination` == -2 ~ -2,  # Mapping "No answer" to -2
    `religious denomination` == -1 ~ -1,  # Mapping "Don't know" to -1
    `religious denomination` == 0  ~ 0,   # Mapping "None" to 0
    `religious denomination` == 1  ~ 1,   # Mapping "Catholic" to 1
    `religious denomination` == 2  ~ 2,   # Mapping "Protestant" to 2
    `religious denomination` == 3  ~ 3,   # Mapping "Orthodox" to 3
    `religious denomination` == 4  ~ 4,   # Mapping "Jew" to 4
    `religious denomination` == 5  ~ 5,   # Mapping "Muslim" to 5
    `religious denomination` == 6  ~ 6,   # Mapping "Hindu" to 6
    `religious denomination` == 7  ~ 7,   # Mapping "Buddhist" to 7
    `religious denomination` == 8  ~ 8,   # Mapping "Other christian" to 8
    `religious denomination` == 9  ~ 2,   # Mapping "Other" to 9
    TRUE ~ NA_integer_                     # All other values will be set to NA
  ))


```
```{r}
library(dplyr)
library(haven)

wave1select <- wave1select %>%
  mutate(`Self positioning in political scale` = as.numeric(zap_labels(`Self positioning in political scale`))) %>%
  filter(`Self positioning in political scale` >= -3)

# And repeat this for the other data frames as needed


wave2select <- wave2select %>%
  mutate(`Self positioning in political scale` = as.numeric(zap_labels(`Self positioning in political scale`))) %>%
  filter(`Self positioning in political scale` >= -3)

wave3select <- wave3select %>%
  mutate(`Self positioning in political scale` = as.numeric(zap_labels(`Self positioning in political scale`))) %>%
  filter(`Self positioning in political scale` >= -3)

wave4select <- wave4select %>%
  mutate(`Self positioning in political scale` = as.numeric(zap_labels(`Self positioning in political scale`))) %>%
  filter(`Self positioning in political scale` >= -3)

```
```{r}


wave1select <- wave1select %>%
  mutate(age = as.numeric(zap_labels(age))) %>%
  filter(age >= 0)

wave2select <- wave2select %>%
  mutate(age = as.numeric(zap_labels(age))) %>%
  filter(age >= 0)

wave3select <- wave3select %>%
  mutate(age = as.numeric(zap_labels(age))) %>%
  filter(age >= 0)

wave4select <- wave4select %>%
  mutate(age = as.numeric(zap_labels(age))) %>%
  filter(age >= 0)

```
```{r}
library(dplyr)

wave1select <- wave1select %>%
  mutate(employment = case_when(
    `employment` %in% 1:3 ~ "Employed",
    `employment` %in% 4:6 ~ "Inactive",
    `employment` == 7     ~ "Unemployed",
    TRUE                        ~ NA_character_  # This will set the other categories as NA
  )) %>%
  # Optional: Remove NA to discard unwanted categories
  filter(!is.na(employment))


```
```{r}
wave2select <- wave2select %>%
  mutate(employment = case_when(
    `employment` %in% 1:3 ~ "Employed",
    `employment` %in% 4:6 ~ "Inactive",
    `employment` == 7     ~ "Unemployed",
    TRUE                         ~ NA_character_  # This will set the other categories as NA
  ))%>%
  # Optional: Remove NA to discard unwanted categories
  filter(!is.na(employment))

```
```{r}
wave3select <- wave3select %>%
  mutate(employment = case_when(
    employment %in% 1:3 ~ "Employed",
    employment %in% 4:6 ~ "Inactive",
    employment == 7     ~ "Unemployed",
    employment == -1    ~ NA_character_, # DK
    employment == -2    ~ NA_character_, # No answer
    employment == -4    ~ NA_character_, # Not asked
    TRUE                ~ "Other"        # Covers 'Other' and any other unspecified codes
  )) %>%
  filter(!is.na(employment)) # Optional: Remove NA to discard unwanted categories

```
```{r}
wave4select <- wave4select %>%
  mutate(employment = case_when(
    employment %in% c(1, 2, 3) ~ "Employed",  # Full time, Part time, and Self-employed
    employment %in% c(4, 5, 6) ~ "Inactive",  # Retired, Housewife, Students
    employment == 7            ~ "Unemployed",# Unemployed
    employment == -1           ~ NA_character_, # Don't know, NA
    employment == -2           ~ NA_character_, # No answer
    employment == -4           ~ NA_character_, # Not asked
    TRUE                       ~ "Other"         # Other and any other unspecified codes
  )) %>%
  filter(!is.na(employment)) # Optional: Remove NA to discard unwanted categories

```


```{r}
wave2select <- wave2select %>%
  mutate(educ = case_when(
    educ == 1 ~ 12,
    educ == 2 ~ 13,
    educ == 3 ~ 14,
    educ == 4 ~ 15,
    educ == 5 ~ 16,
    educ == 6 ~ 17,
    educ == 7 ~ 18,
    educ == 8 ~ 19,
    educ == 9 ~ 20,
    educ == 10 ~ 21,
    educ == -5 ~ -2, # Mapping 'Missing; Unknown; Inappropriate' to 'No answer'
    educ == -4 ~ -4, # 'Not asked' remains the same
    educ == -3 ~ -3, # 'Not applicable (SP: Not studies)' remains the same
    educ == -2 ~ -2, # 'No answer' remains the same
    educ == -1 ~ -2, # Mapping 'Don’t know' to 'No answer'
    TRUE ~ NA_integer_ # Other values will become NA
  ))%>%
  filter(!is.na(educ))

```
```{r}
wave3select<- wave3select %>%
  mutate(educ = case_when(
    educ >= 12 & educ <= 21 ~ educ, # Keep ages 12 to 21 as is
    educ == 0 | educ > 21 ~ NA_integer_, # Set ages out of range 12-21 to NA
    educ == -2 ~ -2,  # NA remains the same
    educ == -1 ~ -2,  # DK (Don't Know) is mapped to No answer
    educ == -4 ~ -4,  # Not asked remains the same
    TRUE ~ NA_integer_ # Set any other values to NA
  ))%>%
  filter(!is.na(educ))

```
```{r}
wave4select <- wave4select %>%
  mutate(educ = case_when(
    educ >= 1 & educ <= 9 ~ educ + 10,   # Adjusting based on the 1-10 range to match 11-20
    educ == 10 ~ 21,                     # Aligning "20 and more" to 21 as in wave 1
    educ == 20 ~ 21,                     # Aligning "20 and more" to 21 as in wave 1
    educ == -5 ~ -2,                     # Mapping 'Missing; Unknown' to 'No answer'
    educ == -4 ~ -4,                     # 'Not asked in survey' remains the same
    educ == -3 ~ -3,                     # 'Not applicable; No formal education' remains the same
    educ == -2 ~ -2,                     # 'No answer' remains the same
    educ == -1 ~ -2,                     # Mapping 'Don’t know' to 'No answer'
    TRUE ~ NA_integer_                   # Set any other values to NA
  ))%>%
  filter(!is.na(educ))

```
```{r}
library(haven)

wave1select <- wave1select %>%
  mutate(across(where(is.labelled), ~as.character(zap_labels(.))))

wave2select <- wave2select %>%
  mutate(across(where(is.labelled), ~as.character(zap_labels(.))))

wave3select <- wave3select %>%
  mutate(across(where(is.labelled), ~as.character(zap_labels(.))))

wave4select <- wave4select %>%
  mutate(across(where(is.labelled), ~as.character(zap_labels(.))))

```

```{r}
wave2select <- wave2select %>%
  mutate(educ = as.character(educ))
wave4select <- wave4select %>%
  mutate(educ = as.character(educ))


```

```{r}
# Step 3: Combine the data frames
  final_df <- bind_rows(wave1select,wave2select,wave3select,wave4select)

# Display the final data frame
print("final_df:")
print(final_df)

```

```{r}

final_df <- final_df %>%
  mutate(`religious denomination` = case_when(
    `religious denomination` == 0  ~ "None",
    `religious denomination` == 1  ~ "Catholic",
    `religious denomination` == 2  ~ "Protestant",
    `religious denomination` == 3  ~ "Orthodox",
    `religious denomination` == 4  ~ "Jew",
    `religious denomination` == 5  ~ "Muslim",
    `religious denomination` == 6  ~ "Hindu",
    `religious denomination` == 7  ~ "Buddhist",
    `religious denomination` == 8  ~ "Other",
    `religious denomination` == -2 ~ "No answer",
    `religious denomination` == -4 ~ "Not asked",
    TRUE ~ NA_character_  # All other values will become NA
  ))


```
```{r}
final_df <- final_df%>%
  mutate(`Self positioning in political scale` = case_when(
    `Self positioning in political scale` == 1 ~ "Left",
    `Self positioning in political scale` == 2 ~ "Left",
    `Self positioning in political scale` == 3 ~ "Left",
    `Self positioning in political scale` == 4 ~ "Left of Center",
    `Self positioning in political scale` == 5 ~ "Center",
    `Self positioning in political scale` == 6 ~ "Right of Center",
    `Self positioning in political scale` == 7 ~ "Right",
    `Self positioning in political scale` == 8 ~ "Right",
    `Self positioning in political scale` == 9 ~ "Right",
    `Self positioning in political scale` == 10 ~ "Right",
    TRUE ~ "Other" # This will catch any other values including NA
  ))

```
```{r}
# This will remove all rows that have NA values in any column
final_df <- na.omit(final_df)

```
```{r}
library(dplyr)

final_df <- final_df %>%
  mutate(across(c(`religious denomination`, 
                  `Self positioning in political scale`,
                  employment, 
                  sex, 
                  cheat, 
                  educ, 
                  `Socio-economic status of respondent`, 
                  Year), factor))
```
```{r}
# List of variables and their desired reference levels
reference_levels <- list(
  `religious denomination`= "None",
  `Self positioning in political scale`= "Center",
  `Socio-economic status of respondent`= "Upper middle class",
  employment="Inactive"
  
  # Add more variables and their reference levels as needed
)

# Loop through the list and relevel each variable
for (var in names(reference_levels)) {
  level <- reference_levels[[var]]
  final_df[[var]] <- relevel(as.factor(final_df[[var]]), ref = level)
}

```

```{r}
# Fit a probit model
probit_model <- glm(cheat ~ , data =final_df , family = binomial(link = "probit"))
```
```{r}
library(margins)

# Calculate the marginal effects
marginal_effects <- margins(probit_model)
```
```{r}
# Assuming probit_model is your fitted model
se <- sqrt(diag(vcov(probit_model)))
coefs_and_se <- cbind(coef(probit_model), se)

```









